### PR TITLE
added auto_update

### PR DESCRIPTION
**Pull request by vitorgalvao**
It’s not very clear where you use `$var` vs `${var}`, so I just made best guesses to keep it in line with your code. Those should be fixed for consistency, though, I’d say.

Changes, all related to updates:

+ `--update` option was missing from help.
+ If the default is to check for updates, but we’re still going to have an `--update` flag that exits on completion, might as well make it install available updates as well.
+ Auto-update is disabled by default (we don’t want to break people’s workflows unexpectedly).
+ When set, this updates the script to its current location and name, whatever those are.

### CODE REVIEW

**Comment by jomo** [comment]
I actually wanted to add this myself a while ago but ended up not doing it because this can be installed via multiple ways:

- Download source
- git
- AUR
- Homebrew
- …

Updating and replacing itself would be inconsistent with all except the first one (which I doubt is the most common method of installation).

Additionally, it would exclude us from Homebrew's [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/19cae6daee368186913ffab6194c6299a12cbfde/share/doc/homebrew/Acceptable-Formulae.md#we-dont-like-tools-that-upgrade-themselves) :/

------

I've addressed the inconsistent variable names in c2fc23ea34cfae9896b965e4e6bea317cb61a9fb, the `--update` option in b34c61ae3e450ea37922158bd1c821720dd946ed, and the counter-intuitive underscored option names in 0fe3bdff43a66e8e0547c903d25142019984c2ac.

Thank you!

**Comment by vitorgalvao** [comment]
But by taking such a stance you’re limiting the usefulness of this tool inside other tools (which the MIT license it good for).

This also doesn’t update the tool itself *unless the user tells it to*, which makes it compatible with such systems because it will never auto-break them. It is essentially the same as the user manually replacing the file (which would also break those systems), but taking less work if you know what you’re doing.

For this reason, it would likely be under the acceptable guidelines for homebrew. They say they don’t like when tools do so, not that they will outright refuse them, and this seems an acceptable feature. Case in point, [`youtube-dl`](https://rg3.github.io/youtube-dl/) can upgrade itself (`-u, `--upgrade`) and [is on the main homebrew repo](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/youtube-dl.rb).

Either way, [I asked](https://github.com/Homebrew/homebrew/issues/46736).

**Comment by jomo** [comment]
You're right, I'll wait for the homebrew issue to be answered.

**Comment by jomo** [comment]
Fixed this via adc23ba6be860da08f6341b7328762f917ad86e5:
I will publish new releases with a special version of `imgur-screenshot.sh` which have [auto-update.patch](https://github.com/jomo/imgur-screenshot/blob/f0871e24ae290a96cf25f32a87352baff261d4e0/auto-update.patch) applied. ([see v1.7.0](https://github.com/jomo/imgur-screenshot/releases/tag/v1.7.0))
The update mechanism checks for
```
https://github.com/jomo/imgur-screenshot/releases/download/${remote_version}/imgur-screenshot.sh
```
and then replaces itself on success.

**Comment by vitorgalvao** [comment]
Great! Thank you.

**Pull request closed without merging**
