### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by jomo**
Three years after the last release, this is the release candidate for version 2.0.0.

The whole thing was mostly rewritten, as 1.x.x turned into a bit of a mess. The code should be a lot cleaner and more stable now. It also features a bunch of improvements and bugfixes, I think nearly all issues have been addressed.

For specific changes please see the commit titles, they should be quite descriptive.

Please note that [`jq`](https://stedolan.github.io/jq/download/) is a new dependency (used to properly parse JSON responses).

The config file is not compatible to version 1.x.x. You can just delete the old config and adjust `~/.config/imgur-screenshot/settings.conf` if necessary.

---

Please let me know if you find any more issues so I can fix them before releasing v2. Thanks all!

### CODE REVIEW

**Comment by Brottweiler** [comment]
Well, it fails for me, but I cannot seem to find where the errors are logged.

**Comment by jomo** [comment]
Can you specify what exactly is failing? Is there any output? Did you modify the config file?

**Comment by Brottweiler** [comment]
As soon as I run imgur-screenshot it literally just says it "failed to take screenshot", nothing else, and that errors have been logged (but i don't know where).

Since you said the old settings were incompatible I've removed the settings and I'm running with defaults.

I ran with `--debug` now and here's the log:
```bash
+ shift
+ initialize
+ declare -g -r CURRENT_VERSION=v1.7.4
+ declare -r CONFIG_HOME=/home/brott/.config
+ '[' -f /home/brott/.config/user-dirs.dirs ']'
+ source /home/brott/.config/user-dirs.dirs
++ XDG_DESKTOP_DIR=/home/brott/Desktop
++ XDG_DOWNLOAD_DIR=/home/brott/Downloads
++ XDG_TEMPLATES_DIR=/home/brott/
++ XDG_PUBLICSHARE_DIR=/home/brott/
++ XDG_DOCUMENTS_DIR=/home/brott/Documents
++ XDG_MUSIC_DIR=/home/brott/Music
++ XDG_PICTURES_DIR=/home/brott/Pictures
++ XDG_VIDEOS_DIR=/home/brott/Videos
+ declare -g -r CONFIG_DIR=/home/brott/.config/imgur-screenshot
+ declare -g -r SETTINGS_PATH=/home/brott/.config/imgur-screenshot/settings.conf
+ declare -g ACCESS_TOKEN REFRESH_TOKEN TOKEN_EXPIRE_TIME
+ declare -g -a UPLOAD_FILES
+ load_default_config
+ declare -g CLIENT_ID=ea6c0ef2987808e
+ declare -g CLIENT_SECRET=5ef4d4efcab40469a62fb2c2f1c9940360f6e504
+ declare -g CREDENTIALS_FILE=/home/brott/.config/imgur-screenshot/credentials.conf
+ declare -g FILE_NAME_FORMAT=imgur-%Y_%m_%d-%H:%M:%S.png
+ declare -g FILE_DIR=/home/brott/Pictures
+ declare -g IMGUR_ICON_PATH=/home/brott/Pictures/imgur.png
+ declare -g NOTIFY_TIME=5000
+ declare -g UPLOAD_CONNECT_TIMEOUT=5
+ declare -g UPLOAD_TIMEOUT=120
+ declare -g UPLOAD_RETRIES=1
+ is_mac
++ uname -s
+ '[' Linux = Darwin ']'
+ declare -g 'SCREENSHOT_SELECT_COMMAND=scrot -s %img'
+ declare -g 'SCREENSHOT_WINDOW_COMMAND=scrot -s -b %img'
+ declare -g 'SCREENSHOT_FULL_COMMAND=scrot %img'
+ declare -g 'OPEN_COMMAND=xdg-open %url'
+ declare -g 'CLIPBOARD_COMMAND=xclip -selection clipboard'
+ declare -g EXIT_ON_ALBUM_CREATION_FAIL=true
+ declare -g LOG_FILE=/home/brott/.config/imgur-screenshot/imgur-screenshot.log
+ declare -g COPY_URL=true
+ declare -g CHECK_UPDATE=true
+ declare -g LOGIN=false
+ declare -g ALBUM_TITLE
+ declare -g ALBUM_ID
+ declare -g OPEN=true
+ '[' 5 -ge 4 ']'
+ declare -g -u MODE=SELECT
+ declare -g 'EDIT_COMMAND=gimp %img'
+ declare -g EDIT=false
+ declare -g AUTO_DELETE
+ declare -g KEEP_FILE=true
+ '[' -f /home/brott/.config/imgur-screenshot/settings.conf ']'
+ parse_args
+ '[' 0 '!=' 0 ']'
+ main
+ check_config
+ local vars
+ vars=(UPLOAD_CONNECT_TIMEOUT UPLOAD_RETRIES UPLOAD_TIMEOUT FILE_NAME_FORMAT FILE_DIR LOG_FILE)
+ '[' false = true ']'
+ vars+=(CLIENT_ID)
+ for var in "${vars[@]}"
+ '[' -z 5 ']'
+ for var in "${vars[@]}"
+ '[' -z 1 ']'
+ for var in "${vars[@]}"
+ '[' -z 120 ']'
+ for var in "${vars[@]}"
+ '[' -z imgur-%Y_%m_%d-%H:%M:%S.png ']'
+ for var in "${vars[@]}"
+ '[' -z /home/brott/Pictures ']'
+ for var in "${vars[@]}"
+ '[' -z /home/brott/.config/imgur-screenshot/imgur-screenshot.log ']'
+ for var in "${vars[@]}"
+ '[' -z ea6c0ef2987808e ']'
+ check_oauth2_client_secrets
+ '[' -z ea6c0ef2987808e ']'
+ '[' -z 5ef4d4efcab40469a62fb2c2f1c9940360f6e504 ']'
+ '[' false = true ']'
+ '[' -n '' ']'
+ '[' -z '' ']'
+ UPLOAD_FILES[0]=
+ for upload_file in "${UPLOAD_FILES[@]}"
+ handle_file ''
+ local img_file edit_cmd
+ '[' -z '' ']'
+ cd /home/brott/Pictures
++ date +imgur-%Y_%m_%d-%H:%M:%S.png
+ img_file=imgur-2019_04_08-16:47:28.png
+ take_screenshot imgur-2019_04_08-16:47:28.png
+ local cmd shot_err
+ echo 'Please select area'
+ is_mac
++ uname -s
+ '[' Linux = Darwin ']'
+ sleep 0.1
+ cmd=SCREENSHOT_SELECT_COMMAND
+ cmd='scrot -s imgur-2019_04_08-16:47:28.png'
+ '[' -z 'scrot -s imgur-2019_04_08-16:47:28.png' ']'
++ scrot -s imgur-2019_04_08-16:47:28.png
+ shot_err=
+ '[' 127 '!=' 0 ']'
+ tee -a /home/brott/.config/imgur-screenshot/imgur-screenshot.log
++ date +%FT%T%z
+ echo '2019-04-08T16:47:28+0200        Failed to take screenshot '\''imgur-2019_04_08-16:47:28.png'\'': '\'''\''. For more information visit https://github.com/jomo/imgur-screenshot/wiki/Troubleshooting'
+ notify error 'Something went wrong :(' 'Information has been logged'
+ is_mac
++ uname -s
+ '[' Linux = Darwin ']'
+ '[' error = error ']'
+ notify-send -a ImgurScreenshot -u critical -c im.error -i /home/brott/Pictures/imgur.png -t 5000 'imgur: Something went wrong :(' 'Information has been logged'
+ exit 1
```

**Comment by Brottweiler** [comment]
Oh, it fails because it can't find scrot. I installed it and now something else happens. Still fails though, but I don't plan to use scrot anyway.

With scrot installed, it fails with this:

```bash
Uploading '/home/brott/Pictures/imgur-2019_04_08-16:51:57.png'...
Upload failed: "{"data":{"id":"PmvuQbS","title":"imgur-2019_04_08-16:51:57","description":null,"datetime":1554735120,"type":"image\/png","animated":false,"width":1240,"height":764,"size":55866,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":0,"is_ad 
```

That error with the "json style syntax" thing shows up in my libnotify as well, not only the terminal.

Is there a default config I can use and modify? maybe it won't fail if I do.

**Comment by jomo** [comment]
It indeed does not create it if it doesn't exist, I corrected that.

The config is read from `$XDG_CONFIG_HOME/imgur-screenshot` or `$HOME/.config/imgur-screenshot`. I should probably update the comment in the source code that refers to the old path.

You can find the config options here: https://github.com/jomo/imgur-screenshot/blob/e83d287e65b36311b207603c00d018621e34c35b/imgur-screenshot#L32-L84

**Comment by Brottweiler** [comment]
Ah, there we go. I've updated my config file and everything seems to work fine!

**Comment by jomo** [comment]
Was anything wrong with the default config, though? I'd like to have a default config that works "out of the box" on most systems, if possible.

**Comment by Brottweiler** [comment]
The only things I've changed in the config are `FILE_DIR` because I prefer to store the screenshot temporarily in `/tmp`, and the screenshot program to `maim`.

Also, I don't want the script to open the image URL in my browser. I prefer to screenshot something, then paste the link to wherever I intended to share the screenshot. Opening it in the browser is nothing I've ever wanted, so I disabled it. Not sure what others think of that.

So the only thing I would change in the default config is this

```diff
diff --git a/imgur-screenshot b/imgur-screenshot
index 794b622..64b346f 100755
--- a/imgur-screenshot
+++ b/imgur-screenshot
@@ -72,7 +72,7 @@ load_default_config() {
   declare -g LOGIN="false"
   declare -g ALBUM_TITLE
   declare -g ALBUM_ID
-  declare -g OPEN="true"
+  declare -g OPEN="false"
   if [ "${BASH_VERSINFO[0]}" -ge "4" ]; then
     declare -g -u MODE="SELECT"
   else
@@ -615,4 +615,4 @@ fi
 
 initialize
 parse_args "${@}"
-main
\ No newline at end of file
+main
```

**Comment by abcarroll** [comment]
First of all, I just want to thank you for all of your work.  I've used this tool for a couple of years now, and -- wow - is it useful.  Thank you.

As far as version 2.0, are you sure jq is really necessary?  I guess it has became popular enough that is has a package in most distro's package repositories, so it's proabbly not as big of a deal as I'm thinking, but if it could gracefully degrade without jq, that would be amazing.  

Aside from that, would you ever consider adding my `--delete-all-from-log` switch?  It's available in [my fork](https://github.com/abcarroll/imgur-screenshot) for the older version.  My code there was written hastily and isn't very pretty (nor am I really that great with bash programming), but I've found it pretty useful.  

Sometimes, I just want screenshots to last days/weeks, so I don't use the `-d` switch, but - ultimately - I find that in the end, I don't care to have months-old screenshots hanging around on imgur.  So, I just wrote a bit that reads the log and deletes any screenshots that weren't already deleted with the `-d` switch, in one big batch.

If you cared to include it in v2, I would happily re-write it for v2 and in a more concise manner.  If you think it's too niche, however, that's understandable as well.

**Comment by jomo** [comment]
Thanks for the feedback, abcarroll.

I do think that `jq` is necessary, as the imgur API relies on JSON and `jq` seems to be the de-facto command line JSON parsing tool. The "parsing" in bash we had before was an unreliable and error-prone hack.

I will reconsider adding support for mass-deletion from the log file!

**Comment by lordlycastle** [comment]
Are we ready to RUMBLE!?

rumble baby rumble

**Comment by jomo** [comment]
Good news, @‌all. I have merged this branch into master and [released v2.0.0](https://github.com/jomo/imgur-screenshot/releases/tag/v2.0.0)! 🎉

**Pull request merged**
